### ISSUE TITLE
Contributors and Admin mentions

### ISSUE THREAD

**Issue by Swastik1710** [Aasthajain123/Mlops_Task#13]
Adding a different line for showing the Admin seperately and making the Contributors Table up to date in the Readme.md file

**Comment by Swastik1710** [comment]
Can I please work on this issue ?

**Comment by Aasthajain123** [comment]
Sure assigning you in some time!

**Comment by Swastik1710** [comment]
Thanks,
Please do add the DWOC and Level labels too.

**Comment by Aasthajain123** [comment]
Will do, thanks!

**Comment by Swastik1710** [comment]
This is how it'll look like.

![Readme PR](https://user-images.githubusercontent.com/71871571/105898606-a5744a00-603f-11eb-94c8-8625d3b6913d.jpg)

**Comment by Aasthajain123** [comment]
Sure
Will assign.

**Comment by Swastik1710** [comment]
Hey @Aasthajain123, please assign it to me so that I can make a PR.

**Comment by Aasthajain123** [comment]
Yaa sure.
Regards
Aastha Jain.

**Comment by Swastik1710** [comment]
I've made a PR regarding the same.
Please have a look.

**Comment by Aasthajain123** [comment]
Sure, I'll take a look.
