### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [Aasthajain123/Mlops_Task#2]
Like this
![image](https://user-images.githubusercontent.com/68433936/104811157-a3c8ac00-581f-11eb-8dab-11878e653c11.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by Aasthajain123** [comment]
Sure!
Go ahead with it.
Best wishes.

**Comment by Aasthajain123** [comment]
Assigned
Go ahead!
