### ISSUE TITLE
Add Issue Template

### ISSUE THREAD

**Issue by muthuannamalai12** [Aasthajain123/Mlops_Task#26]
Would like to add issue templates to these project that will basically explain the type of issue and its description.

**Comment by muthuannamalai12** [comment]
@Aasthajain123 Kindly assign me this issue as a part of DWOC. I would love to work on this issue

**Comment by muthuannamalai12** [comment]
@Aasthajain123 Can I start Working

**Comment by Aasthajain123** [comment]
Yes, go ahead.
