### ISSUE TITLE
Integrate Welcome and Greeting Bot

### ISSUE THREAD

**Issue by samir-0711** [Aasthajain123/Mlops_Task#3]
I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message

**Comment by samir-0711** [comment]
I would like to work on this.

Kindly do add the DWOC and Level label

**Comment by Aasthajain123** [comment]
Sure
Go ahead!
All the best.

**Comment by Aasthajain123** [comment]
Assigned
Go ahead.
