### ISSUE TITLE
CODE OF CONDUCT FILE

### ISSUE THREAD

**Issue by samir-0711** [Aasthajain123/Mlops_Task#4]
There is no code of conduct file in this repository
code of conduct is a file that will be required to a open source project for the contributors to follow the decorum
Kindly let me know if you can assign me this issue

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by Aasthajain123** [comment]
Sure
Go ahead!
Work on it , I will check once done.
All the best.

**Comment by Aasthajain123** [comment]
I have Assigned.
You can go ahead.
