### ISSUE TITLE
CONTRIBUTING FILE 

### ISSUE THREAD

**Issue by akrish4** [Aasthajain123/Mlops_Task#5]
Hi @Aasthajain123 
I would like to add a contributing.md file which will contain all contributing guidlines so that all contributors can follow 

Kindly assign me issue and also add DWOC and Level label

**Comment by Aasthajain123** [comment]
Firstly complete the previous task , the one which I have already assigned
to you.

**Comment by akrish4** [comment]
Hi @Aasthajain123  
Now can you assign me
